{
 "title": "Alert Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "policyId",
    "label": "Configuration Policy",
    "query": "select id as __value, name as __text from configuration_policy"
   }
  ]
 },
 "panels": [
  {
   "title": "Configuration Policy Compliance",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (policyId, systemId) (fuse_configuration_policy_compliance_failures{policyId=~\"[[policyId]]\",})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Systems Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(otcs_heartbeat_cside_mode{systemId=~\".+\",}) by (systemId)",
     "legendFormat": "CSIDE Mode"
    },
    {
     "expr": "max(otcs_heartbeat_pending_restart{systemId=~\".+\",}) by (systemId)",
     "legendFormat": "Pending Restart"
    },
    {
     "expr": "sum(fuse_system_active{systemId=~\".+\",}) by (systemId)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(otcs_heartbeat_up{systemId=~\".+\",})  by (systemId)",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Storage Providers List",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Write Throughput"
    },
    {
     "expr": "avg(otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Read Throughput"
    },
    {
     "expr": "(avg(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\",}) by (componentName, type, envId))  - (avg(otcs_storage_provider_disk_space_used{systemId=~\"[[systemId]]\",}) by (componentName, type, envId))",
     "legendFormat": "Free Space"
    },
    {
     "expr": "avg(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\",}) by (componentName, type, envId)",
     "legendFormat": "Total Space"
    },
    {
     "expr": "avg(otcs_storage_provider_disk_space_used{systemId=~\"[[systemId]]\",}) by (componentName, type, envId)",
     "legendFormat": "Total Used Space"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(fuse_environment_active) by (envId)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Admin Server Systems Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_system_admin_server{envId=~\"[[envId]]\"})",
     "legendFormat": "Admin Server"
    }
   ]
  }
 ]
}