{
 "title": "Archive Center System Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "barInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "overviewChartBarInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "barIntervalLarge",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(otac_read_performance{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) * 1000000",
     "legendFormat": "Avg. Read Throughput "
    },
    {
     "expr": "avg(otac_write_performance{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) * 1000000",
     "legendFormat": "Avg. Write Throughput "
    }
   ]
  },
  {
   "title": "Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(increase(otac_read_data_volume_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) * 1000000 and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Read Data Volume"
    },
    {
     "expr": "max(increase(otac_write_data_volume_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) * 1000000 and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Write Data Volume"
    }
   ]
  },
  {
   "title": "Component",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max(increase(otac_read_components_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Read Components"
    },
    {
     "expr": "max(increase(otac_write_components_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Write Components"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_memory_used{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "max(otcs_resource_memory_total{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "System Disks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(otcs_resource_disk_space_used{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint) / max(otcs_resource_disk_space_total{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint)",
     "legendFormat": "Used Space - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (severity, alertname, componentId, componentName, componentClass) (ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring(severity) ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count(fuse_configuration_policy_system{systemId=~\"[[systemId]]\",} and on (policyId) fuse_configuration_policy_active == 1)",
     "legendFormat": "Configuration Policies"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\",} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\",}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",systemId=~\"[[systemId]]\",severity=\"error\",}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "max(otac_storage_manager_up{systemId=~\"[[systemId]]\",}) or vector(0)",
     "legendFormat": "Storage Manager Status"
    },
    {
     "expr": "max(otcs_heartbeat_last_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Last Heart Beat"
    },
    {
     "expr": "max(fuse_maintenance_window_start_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Maintenance Mode"
    }
   ]
  },
  {
   "title": "Storage Manager Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(otac_storage_manager_up{systemId=~\"[[systemId]]\",}) or vector(0)",
     "legendFormat": "Storage Manager Status"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(otcs_resource_memory_total{systemId=~\"[[systemId]]\"})",
     "legendFormat": "RAM Total Memory"
    },
    {
     "expr": "sum(otcs_resource_swap_memory_total{systemId=~\"[[systemId]]\"})",
     "legendFormat": "RAM SWAP Total Memory"
    },
    {
     "expr": "sum(otcs_resource_service_uptime{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Service Uptime"
    },
    {
     "expr": "sum(otcs_resource_system_uptime{systemId=~\"[[systemId]]\"})",
     "legendFormat": "System Uptime"
    }
   ]
  },
  {
   "title": "Document Pipelines Queues Index",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (componentId, componentName, componentClass) (otac_dp_queue_idx{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Avg. Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum(sum_over_time(fuse_system_active{systemId=~\"[[systemId]]\"}[${__range_s}s]))) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:perf{systemId=~\"[[systemId]]\",}) or vector(0)",
     "legendFormat": "Performance"
    }
   ]
  }
 ]
}