{
 "title": "Configuration Policies",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "policyId",
    "label": "Configuration Policy",
    "query": "select id as __value, name as __text from configuration_policy"
   }
  ]
 },
 "panels": [
  {
   "title": "Systems Online",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (systemId) (otcs_heartbeat_up{systemId=~\"[[systemId]]\",})",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "System Compliance",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (systemId) (fuse_configuration_policy_compliance_failures{systemId=~\"[[systemId]]\",policyId=~\"[[policyId]]\",})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Configuration Policy Compliance",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (policyId) (fuse_configuration_policy_compliance_failures{policyId=~\"[[policyId]]\",})",
     "legendFormat": "Failures"
    }
   ]
  }
 ]
}