{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "barInterval",
    "query": "1m,10m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "barIntervalLarge",
    "query": "1m,10m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (severity, alertname) (ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(fuse_system_active{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Systems Total"
    },
    {
     "expr": "count(ALERTS{alertname=\"heartbeat_missing\",envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Systems Offline"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "System Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "System Errors"
    },
    {
     "expr": "count(fuse_configuration_policy_active) or vector(0)",
     "legendFormat": "Config. Policies Total"
    },
    {
     "expr": "count(max by (systemId) (fuse_configuration_policy_compliance_failures{envId=~\"[[envId]]\"} > 0 )) or vector(0)",
     "legendFormat": "Config. Policies Warnings"
    },
    {
     "expr": "sum(max by (envId) (otcs_agent_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Agents"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Agent Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Agent Warnings"
    },
    {
     "expr": "sum(max by (policyId) (fuse_configuration_policy_compliance_failures{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Config. Policies Non Compliant"
    },
    {
     "expr": "sum(max by (systemId) (otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Systems Online"
    },
    {
     "expr": "count(fuse_configuration_policy_active == 1) or vector(0)",
     "legendFormat": "Config. Policies Active"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\"} and otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Content Overview",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (envId, componentName) (topk(5, sum by (envId, componentName) (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type))))) or sort_desc(sum by (envId, componentName) (label_replace(sum  (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type)) - sum (topk(5, sum by (envId, componentName) (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type)))),\"componentName\",\"Other\",\"componentName\",  \"(.*)\")) > 0)",
     "legendFormat": "{{componentName}} {{envId}}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(otcs_users_total_active{envId=~\"[[envId]]\"}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg(otcs_resource_memory_used{envId=~\"[[envId]]\"} and otcs_heartbeat_up{envId=~\"[[envId]]\"})/max(otcs_resource_memory_total{envId=~\"[[envId]]\"} and otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Avg. Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[${__range_s}s])) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\"}[${__range_s}s])) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio:avg_1h{envId=~\"[[envId]]\"} and on (envId) system_env:otcs_heartbeat_up:max_1h{envId=~\"[[envId]]\"})",
     "legendFormat": "Threads Usage"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(otcs_queuetables_d_tree_notify{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "DTree Notify"
    },
    {
     "expr": "max(otcs_queuetables_ll_event_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": " LLEvent Queue"
    },
    {
     "expr": "max(otcs_queuetables_notify_events{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Notify Events"
    },
    {
     "expr": "max(otcs_queuetables_notify_messages{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Notify Messages"
    },
    {
     "expr": "max(otcs_queuetables_provider_retry{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Provider Retry"
    },
    {
     "expr": "max(otcs_queuetables_rendition_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Rendition Queue"
    },
    {
     "expr": "max(otcs_queuetables_worker_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Worker Queue"
    },
    {
     "expr": "max(otcs_queuetables_worker_queue_pending{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Worker Queue Pending"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Avg. Performance"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current{envId=~\"[[envId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$__range])) by (envId, currentRequest))",
     "legendFormat": "{{currentRequest}}"
    }
   ]
  },
  { "title": "SOV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "System Object Volumes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})) + (count(count by (envId) (ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)) or vector(0)",
     "legendFormat": "Admin Servers Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Admin Servers Active"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Admin Servers Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})) or sum(count by (envId, componentId, componentName, componentClass) (otcs_sov_processes_status{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Running"
    },
    {
     "expr": "sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\", severity=\"error\"})) or vector(0)",
     "legendFormat": "Processes Errors"
    },
    {
     "expr": "sum(max by (envId) (otcs_sov_partition_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Partitions Total"
    },
    {
     "expr": "sum(count by (envId) (ALERTS{alertname!~\"^__.*$\", componentClass=\"partition\", envId=~\"[[envId]]\", severity=\"error\"})) or vector(0)",
     "legendFormat": "Partitions Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_pending{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Pending"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Quarantined"
    },
    {
     "expr": "count(count by (envId, alertname, severity) (ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"warning\"} unless ignoring (severity) ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"} or ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"})) * sum(count by (envId) ((otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}) > 0)) or vector(0)",
     "legendFormat": "iPools Quarantined Count Alert"
    }
   ]
  },
  {
   "title": "Ipools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_pending{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Quarantined"
    }
   ]
  },
  { "title": "DA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Distributed Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(otcs_da_agents_total_count{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Agents Total"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Agents Errors"
    },
    {
     "expr": "sum(otcs_da_workers_total_count{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Total"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Workers Errors"
    },
    {
     "expr": "count(count by (envId) (otcs_da_agents_total_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Environments"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_backlog{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Backlog"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_queued{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Queued"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_processed{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Processed"
    }
   ]
  },
  {
   "title": "Distributed Agents Pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max by (envId) (otcs_da_queue_backlog{envId=~\"[[envId]]\"}) and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Backlog"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_queued{envId=~\"[[envId]]\"}) and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_processed{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max(fuse_environment_active) by (envId)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Ipools Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_pending{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval]))) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval]))) or vector(0)",
     "legendFormat": "Quarantined"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max(fuse_environment_active) by (envId)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Distributed Agents Pie",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(max by (envId) (otcs_da_queue_backlog{envId=~\"[[envId]]\"}) and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Backlog"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_queued{envId=~\"[[envId]]\"}) and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_processed{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Distributed Agents Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_processed{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_queued{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_backlog{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Backlog"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max(fuse_environment_active) by (envId)",
     "legendFormat": "Active"
    }
   ]
  },
  { "title": "OTAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Logical Archives",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_original_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Original Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_original_archives_count{envId=~\"[[envId]]\"})) - \r\ncount(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Original Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Original Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_replicated_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Replicated Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_replicated_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Replicated Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Replicated Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_external_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "External Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_external_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "External Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"error\"}) or vector(0)",
     "legendFormat": "External Errors"
    }
   ]
  },
  {
   "title": "Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(increase(otac_read_data_volume_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) * 1000000 and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Read Data Volume"
    },
    {
     "expr": "max(increase(otac_write_data_volume_total{systemId=~\"[[systemId]]\"}[$barIntervalLarge]) * 1000000 and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Write Data Volume"
    }
   ]
  }
 ]
}