{
 "title": "Distributed Agents",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   }
  ]
 },
 "panels": [
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(otcs_da_agents_total_count{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents"
    },
    {
     "expr": "sum(otcs_da_agents_status_count{systemId=~\"[[systemId]]\", status=\"2\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents Stopped"
    },
    {
     "expr": "sum(otcs_da_workers_total_count{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers"
    },
    {
     "expr": "sum(otcs_da_workers_status_count{systemId=~\"[[systemId]]\", status=\"2\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Stopped"
    },
    {
     "expr": "sum(otcs_da_workers_status_count{systemId=~\"[[systemId]]\", status=\"3\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Paused"
    },
    {
     "expr": "sum(otcs_da_workers_status_count{systemId=~\"[[systemId]]\", status=\"0\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Idle"
    },
    {
     "expr": "sum(otcs_da_workers_status_count{systemId=~\"[[systemId]]\", status=\"5\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Offline"
    },
    {
     "expr": "sum(otcs_da_workers_status_count{systemId=~\"[[systemId]]\", status=\"1\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Workers Running"
    },
    {
     "expr": "sum(otcs_da_agents_status_count{systemId=~\"[[systemId]]\", status=\"4\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents Standing By"
    },
    {
     "expr": "sum(otcs_da_agents_status_count{systemId=~\"[[systemId]]\", status=\"1\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents Running"
    },
    {
     "expr": "sum(otcs_da_agents_status_count{systemId=~\"[[systemId]]\", status=\"0\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents Idle"
    },
    {
     "expr": "sum(otcs_da_agents_status_count{systemId=~\"[[systemId]]\", status=\"5\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Distributed Agents Offline"
    },
    {
     "expr": "sum(otcs_da_total_task_error{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Task Errors"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(fuse_environment_active{envId=~\".+\"}) by (envId)"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(fuse_system_active{systemId=~\".+\",}) by (systemId)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(otcs_heartbeat_up{systemId=~\".+\",})  by (systemId)",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Distributed Agents",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(otcs_da_queue_queued{systemId=~\"[[systemId]]\", } and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queued ({{envId}})"
    },
    {
     "expr": "avg(otcs_da_queue_processed{systemId=~\"[[systemId]]\", } and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Processed ({{envId}})"
    },
    {
     "expr": "avg(otcs_da_queue_backlog{systemId=~\"[[systemId]]\", } and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Backlog ({{envId}})"
    }
   ]
  },
  {
   "title": "Distributed Agent Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max (otcs_da_agent_status{systemId=~\"[[systemId]]\",}) by (componentId, componentClass, componenteName, systemId, envId)",
     "legendFormat": "Status"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",adminAlert!=\"true\",systemId=~\"[[systemId]]\", componentClass=\"da_agent\", severity=\"error\"}) by (componentName, componentId, componentClass, systemId, envId) or 0 * count by (componentName, componentId, componentClass, systemId, envId) (otcs_da_agent_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\", componentClass=\"da_agent\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\", componentClass=\"da_agent\"}) by (componentName, componentId, componentClass, systemId, envId) or 0 * count by (componentName, componentId, componentClass, systemId, envId) (otcs_da_agent_status{systemId=~\"[[systemId]]\"}) ",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "max (otcs_da_worker_status{systemId=~\"[[systemId]]\",}) by (componentId, componentClass, componenteName, systemId, envId)",
     "legendFormat": "Status"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",adminAlert!=\"true\",systemId=~\"[[systemId]]\", componentClass=\"da_worker\", severity=\"error\"}) by (componentId, componentName, componentClass, systemId, envId) or 0 * count by (componentId, componentName, componentClass, systemId, envId) (otcs_da_worker_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\", componentClass=\"da_worker\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\", componentClass=\"da_worker\"}) by (componentId, componentName, componentClass, systemId, envId) or 0 * count by (componentId, componentName, componentClass, systemId, envId) (otcs_da_worker_status{systemId=~\"[[systemId]]\"}) ",
     "legendFormat": "Warnings"
    }
   ]
  }
 ]
}