{
 "title": "Reports",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   {
    "name": "barInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   }
  ]
 },
 "panels": [
  {
   "title": "Document Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envId) (otcs_storage_provider_total_files{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"})",
     "legendFormat": "Total Files"
    },
    {
     "expr": "sum by (envId) (otcs_storage_provider_total_versions{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"})",
     "legendFormat": "Total Versions"
    }
   ]
  },
  {
   "title": "Storage Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (envId) (otcs_storage_provider_document_size{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"} / 1.024e+9)",
     "legendFormat": "Document Size"
    }
   ]
  },
  {
   "title": "Available Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(count_over_time(fuse_system_active:count_1h{systemId=~\"[[systemId]]\"}[$__range])) by (envId)",
     "legendFormat": "Counter"
    }
   ]
  },
  {
   "title": "Systems by Environment and Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by (envId, systemType) (max_over_time(fuse_system_active{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\",systemType!=\"\"}[$__range]) == 1)",
     "legendFormat": "Counter"
    }
   ]
  },
  { "title": "OTAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by (envId, systemId) (otac_read_performance{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by (envId, systemId) (otac_write_performance{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Write Throughput"
    }
   ]
  },
  {
   "title": "Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "round(increase(otac_read_data_volume_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$barInterval]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Read Data Volume"
    },
    {
     "expr": "round(increase(otac_write_data_volume_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$barInterval]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Write Data Volume"
    }
   ]
  },
  {
   "title": "Component",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "round(increase(otac_read_components_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$barInterval]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Read Components"
    },
    {
     "expr": "round(increase(otac_write_components_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$barInterval]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Write Components"
    }
   ]
  },
  {
   "title": "OTAC Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (systemId, envId) (increase(otac_read_data_volume_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$__range]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Total Read Data Volume"
    },
    {
     "expr": "sum by (systemId, envId) (increase(otac_write_data_volume_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$__range]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Total Write Data Volume"
    },
    {
     "expr": "avg by (envId, systemId) (avg_over_time(otac_read_performance{systemId=~\"[[systemId]]\",}[$__range]))",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by (envId, systemId) (avg_over_time(otac_write_performance{systemId=~\"[[systemId]]\",}[$__range]))",
     "legendFormat": "Avg. Write Throughput"
    },
    {
     "expr": "sum by (systemId, envId) (increase(otac_read_components_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$__range]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Total Read Components"
    },
    {
     "expr": "sum by (systemId, envId) (increase(otac_write_components_total{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[$__range]) and on(systemId, envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "Total Write Components"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Alerts by Component and Severity",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[$__range])))  by (severity, componentType) > 0 or sum by (severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) != 0 )",
     "legendFormat": "{{componentType}}"
    },
    {
     "expr": "sum(round(increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[$__range])))  by (severity, componentType) > 0 or sum by (severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) != 0 )",
     "legendFormat": "{{componentType}}"
    }
   ]
  },
  {
   "title": "Alerts by Environment and Severity",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (severity, envId) (round(sum by (severity, envId, componentType) (increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) > 0)) or sum by (envId, severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) != 0 ))",
     "legendFormat": "{{envId}} - {{severity}}"
    },
    {
     "expr": "sum by (severity, envId) (round(sum by (severity, envId, componentType) (increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) > 0)) or sum by (envId, severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) != 0 ))",
     "legendFormat": "{{envId}} - {{severity}}"
    }
   ]
  },
  {
   "title": "MTTR",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (componentType) ((rate(fuse_alert_lasted_time_total:rate_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\"}[$__range]) > 0) / (rate(fuse_alert_count_total:rate_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\"}[$__range]) > 0) or max  by (componentType) (max_over_time(fuse_alert_lasted_time_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\"}[$__range]) != 0)) / 60",
     "legendFormat": "{{componentType}}"
    }
   ]
  },
  {
   "title": "Alerts by Component",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]))  by (componentType) > 0 or sum by (componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", componentType!~\"OTAC_.*|HEALTH\"}[$__range]) != 0)",
     "legendFormat": "{{componentType}}"
    }
   ]
  },
  {
   "title": "Alerts by Environment Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (severity) (round(sum by (severity, envId, componentType) (increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[${barInterval}]) > 0)) or sum by (envId, severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\", componentType!~\"OTAC_.*|HEALTH\"}[${barInterval}]) != 0 ))",
     "legendFormat": "{{severity}}"
    },
    {
     "expr": "sum by (severity) (round(sum by (severity, envId, componentType) (increase(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[${barInterval}]) > 0)) or sum by (envId, severity, componentType) (max_over_time(fuse_alert_count_total:max_1h{envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\", componentType!~\"OTAC_.*|HEALTH\"}[${barInterval}]) != 0 ))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  { "title": "Management Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Availability Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "count by (envId, systemId) (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) < 0.95) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "< 95%"
    },
    {
     "expr": "count by (envId, systemId) (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) >= 0.95) and (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) <= 0.99) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 95% and <= 99%"
    },
    {
     "expr": "count by (envId, systemId) (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) >= 0.99) and (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) <= 0.995) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 99% and <= 99.5%"
    },
    {
     "expr": "count by (envId, systemId) (sum by (envId, systemId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) > 0.995) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "> 99.5%"
    }
   ]
  },
  {
   "title": "Availability Overview by Env",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "count by (envId) (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) < 0.95) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "< 95%"
    },
    {
     "expr": "count by (envId) (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) >= 0.95) and (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) <= 0.99) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 95% and <= 99%"
    },
    {
     "expr": "count by (envId) (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) >= 0.99) and (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) <= 0.995) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 99% and <= 99.5%"
    },
    {
     "expr": "count by (envId) (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) >= 0.95) and (sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s])) <= 0.995) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "> 99.5%"
    }
   ]
  },
  {
   "title": "Alerts Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "floor(sum by (systemId, envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", systemId=~\"[[systemId]]\", severity=\"WARNING\"}[$__range]))) + floor(sum by (systemId, envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", systemId=~\"[[systemId]]\", severity=\"ERROR\"}[$__range])))",
     "legendFormat": "Total"
    },
    {
     "expr": "floor(sum by (envId, systemId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", systemId=~\"[[systemId]]\", severity=\"ERROR\"}[$__range])))",
     "legendFormat": "Errors"
    },
    {
     "expr": "floor(sum by (systemId, envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", systemId=~\"[[systemId]]\", severity=\"WARNING\"}[$__range])))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Alerts Overview by Env",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "floor(sum by (envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\"}[$__range]))) + floor(sum by (envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\"}[$__range])))",
     "legendFormat": "Total"
    },
    {
     "expr": "floor(sum by (envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"ERROR\"}[$__range])))",
     "legendFormat": "Errors"
    },
    {
     "expr": "floor(sum by (envId) (increase(fuse_alert_count_total:max_1h{componentType!~\"OTAC_.*|HEALTH\", envId=~\"[[envId]]\", systemId=~\"[[systemId]]|null\", severity=\"WARNING\"}[$__range])))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "count by (envId, systemId) (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) < 0.1) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "< 10%"
    },
    {
     "expr": "count by (envId, systemId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) >= 0.1) and (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) <= 0.5)) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 10% and <= 50%"
    },
    {
     "expr": "count by (envId, systemId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) >= 0.51) and (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) <= 0.9)) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 51% and <= 90%"
    },
    {
     "expr": "count by (envId, systemId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) > 0.9)) or (0 * (sum by (envId, systemId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]))))",
     "legendFormat": "> 90%"
    }
   ]
  },
  {
   "title": "Performance Overview by Env",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "count by (envId) (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) < 0.1) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": "< 10%"
    },
    {
     "expr": "count by (envId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) >= 0.1) and (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) <= 0.5)) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 10% and <= 50%"
    },
    {
     "expr": "count by (envId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) >= 0.51) and (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) <= 0.9)) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\"}[${__range_s}s]))))",
     "legendFormat": ">= 51% and <= 90%"
    },
    {
     "expr": "count by (envId) ((avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]) > 0.9)) or (0 * (sum by (envId) (sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\",}[${__range_s}s]))))",
     "legendFormat": "> 90%"
    }
   ]
  },
  { "title": "Performance and Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Performance by Environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(avg by (envId) (avg_over_time(system_env:perf:avg_1h{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[${barInterval}]) * 100) or 0 * (count by (envId) (count_over_time(fuse_system_active:count_1h{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[${barInterval}]))))",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Availability by Environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum by (envId) (sum_over_time(otcs_heartbeat_up:sum_1h{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[${barInterval}])) / (sum by (envId)(sum_over_time(fuse_system_active:sum_1h{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[${barInterval}]))) * 100) or 0 * (sum by (envId) (count_over_time(fuse_system_active:count_1h{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[${barInterval}])))",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Threads Usage by Environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (envId) (system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Threads Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (systemId) (system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{systemId}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envId) (irate(otcs_socket_requests_valid_total{systemId=~\"[[systemId]]\",}[1m]) and on(envId) max_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[1m]))",
     "legendFormat": "Total Valid Requests"
    },
    {
     "expr": "sum by (envId) (irate(otcs_socket_requests_invalid_total{systemId=~\"[[systemId]]\",}[1m]) and on(envId) max_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[1m]))",
     "legendFormat": "Total Invalid Requests"
    },
    {
     "expr": "sum by (envId) (irate(otcs_socket_requests_timeout_total{systemId=~\"[[systemId]]\",}[1m]) and on(envId) max_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}[1m]))",
     "legendFormat": "Total Timeout Requests"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envId) (otcs_users_total_active{systemId=~\"[[systemId]]\",} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Avg. Queue Time by Environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (envId) (system_env:otcs_thread_queue_avg:avg{systemId=~\"[[systemId]]\",} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Avg. Queue Time by System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (systemId) (system_env:otcs_thread_queue_avg:avg{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{systemId}}"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current:max_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range])) by (currentRequest))",
     "legendFormat": "{{currentRequest}}"
    }
   ]
  },
  {
   "title": "Avg. Queue Tables",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (envId) (avg_over_time(otcs_queuetables_d_tree_notify:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "DTree Notify"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_ll_event_queue:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": " LLEvent Queue"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_notify_events:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Notify Events"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_notify_messages:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Notify Messages"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_provider_retry:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Provider Retry"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_rendition_queue:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Rendition Queue"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_worker_queue:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Worker Queue"
    },
    {
     "expr": "avg by (envId)(avg_over_time(otcs_queuetables_worker_queue_pending:avg_1h{systemId=~\"[[systemId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up:max_1h{systemId=~\"[[systemId]]\"}[$__range]))",
     "legendFormat": "Worker Queue Pending"
    }
   ]
  },
  { "title": "Host Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Avg. CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (envId) (otcs_resource_system_cpu_load{systemId=~\"[[systemId]]\",} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"})",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "CPU by System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "otcs_resource_system_cpu_load{systemId=~\"[[systemId]]\",} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}",
     "legendFormat": "{{systemId}}"
    }
   ]
  },
  {
   "title": "Avg. Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (envId) (otcs_resource_memory_used{systemId=~\"[[systemId]]\"} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}) / 1.024e+9",
     "legendFormat": "{{envId}}"
    }
   ]
  },
  {
   "title": "Memory Usage by System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(otcs_resource_memory_used{systemId=~\"[[systemId]]\"} and on(envId) otcs_heartbeat_up{systemId=~\"[[systemId]]\", envId=~\"[[envId]]\"}) / 1.024e+9",
     "legendFormat": "{{systemId}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(otcs_resource_disk_space_used{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint) / max(otcs_resource_disk_space_total{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}