{
 "title": "Storage Providers",
 "description": "Storage Providers page",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "spType",
    "label": "Storage Provider Type",
    "query": "RDBMS,EXTSHARED,ENTERPRISEARCHIVE"
   },
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   { "name": "componentName", "label": "Component Name", "query": "Default" }
  ]
 },
 "panels": [
  {
   "title": "Storage Providers List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Write Throughput"
    },
    {
     "expr": "avg(otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Read Throughput"
    },
    {
     "expr": "(avg(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\",}) by (componentName, type, envId))  - (avg(otcs_storage_provider_disk_space_used{systemId=~\"[[systemId]]\",}) by (componentName, type, envId))",
     "legendFormat": "Free Space"
    },
    {
     "expr": "avg(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\",}) by (componentName, type, envId)",
     "legendFormat": "Total Space"
    },
    {
     "expr": "avg(otcs_storage_provider_disk_space_used{systemId=~\"[[systemId]]\",}) by (componentName, type, envId)",
     "legendFormat": "Total Used Space"
    },
    {
     "expr": "avg(otcs_storage_provider_file_size{systemId=~\"[[systemId]]\",}) by (componentName, type, envId)",
     "legendFormat": "File Size"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": " sum by (severity, alertname, componentId, systemId, envId) (ALERTS{alertname!~\"__.*\",envId=~\"[[envId]]\",componentClass=\"storage_provider\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",envId=~\"[[envId]]\",componentClass=\"storage_provider\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",envId=~\"[[envId]]\",componentClass=\"storage_provider\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Content Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(otcs_content_status_size{envId=~\"[[envId]]\", type=~\"[[spType]]\", componentName=~\"[[componentName]]\"}) by (type, componentName, envId)",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Storage Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (envId) (otcs_storage_provider_document_size{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"})",
     "legendFormat": "Document Size  in {{componentName}} {{envId}}"
    }
   ]
  },
  {
   "title": "Document Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envId) (otcs_storage_provider_total_files{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"})",
     "legendFormat": "Total Files in {{componentName}} {{envId}}"
    },
    {
     "expr": "sum by (envId) (otcs_storage_provider_total_versions{systemId=~\"[[systemId]]\",envId=~\"[[envId]]\"})",
     "legendFormat": "Total Versions in {{componentName}} {{envId}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg(otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\",type=~\"[[spType]]\", componentName=~\"[[componentName]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Avg. Read Throughput {{componentName}} ({{envId}})"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg(otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\",type=~\"[[spType]]\", componentName=~\"[[componentName]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (componentName, type, envId)",
     "legendFormat": "Avg. Write Throughput {{componentName}} ({{envId}})"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\"}) - sum(otcs_storage_provider_disk_space_used{systemId=~\"[[systemId]]\",})",
     "legendFormat": "Total Free Space"
    },
    {
     "expr": "sum(otcs_storage_provider_disk_space_total{systemId=~\"[[systemId]]\"}) ",
     "legendFormat": "Total Disk Space"
    },
    {
     "expr": "count (ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",componentClass=\"storage_provider\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",componentClass=\"storage_provider\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count (ALERTS{alertname!~\"__.*\",systemId=~\"[[systemId]]\",componentClass=\"storage_provider\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "avg(otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\", type=~\"[[spType]]\"}) or vector(0)",
     "legendFormat": "Avg. Write Throughput"
    },
    {
     "expr": "avg(otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\", type=~\"[[spType]]\"}) or vector(0)",
     "legendFormat": "Avg. Read Throughput"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max(fuse_environment_active{envId=~\".+\"}) by (envId)"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(fuse_system_active{systemId=~\".+\",}) by (systemId)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(otcs_heartbeat_up{systemId=~\".+\",})  by (systemId)",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Blacklisted",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "min(otcs_storage_provider_blacklisted{envId=~\"[[envId]]\"}) by (envId, systemId, componentId, componentName)",
     "legendFormat": "blackListed"
    }
   ]
  }
 ]
}