{
 "title": "System Details",
 "time": { "from": "2024-02-24T11:42:14.343Z", "to": "2024-02-28T11:42:14.345Z" },
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   }
  ]
 },
 "panels": [
  {
   "title": "Worker Agents Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "DA Agents Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Agents Detail",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",systemId=~\"[[systemId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{systemId=~\"[[systemId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (severity, alertname, componentId, componentName, componentClass, systemId, envId) (ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",}) and (max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}))",
     "legendFormat": "Threads Usage"
    },
    {
     "expr": "avg(avg_over_time(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",}[5m])) and (max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}))",
     "legendFormat": "Avg. Threads Usage"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(otcs_thread_execution_time_total{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Avg. Execution Time"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{systemId=~\"[[systemId]]\",}) and (max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "System Disks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(otcs_resource_disk_space_used{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint) / max(otcs_resource_disk_space_total{systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, mountpoint)",
     "legendFormat": "Used Space - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Database Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(otcs_db_query_execution_time{componentClass=\"db_performance\",systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (componentId)",
     "legendFormat": "{{componentId}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_memory_used{systemId=~\"[[systemId]]\",}) and (max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}))",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "max(otcs_resource_memory_total{systemId=~\"[[systemId]]\",}) and (max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}))",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_queue_avg:avg{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue Average"
    },
    {
     "expr": "min(system_env:otcs_thread_queue_min:min{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue Min"
    },
    {
     "expr": "max(system_env:otcs_thread_queue_max:max{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in:sum{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue Depth In"
    },
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in_max:sum{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue Depth Max"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(otcs_socket_requests_valid_total{systemId=~\"[[systemId]]\",}[1m])) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Valid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_invalid_total{systemId=~\"[[systemId]]\",}[1m])) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Invalid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_timeout_total{systemId=~\"[[systemId]]\",}[1m])) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Timeout Requests"
    },
    {
     "expr": "sum(otcs_socket_exceptions_total{systemId=~\"[[systemId]]\",}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Exceptions"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"}[$__range]) and on(systemId) max_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}[$__range])) by (systemId, currentRequest))",
     "legendFormat": "{{currentRequest}}"
    }
   ]
  },
  {
   "title": "Throughput RDBMS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\", type=\"RDBMS\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Read Throughput"
    },
    {
     "expr": "otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\", type=\"RDBMS\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Write Throughput"
    }
   ]
  },
  {
   "title": "Throughput EXTSHARED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\", type=\"EXTSHARED\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Read Throughput MBs"
    },
    {
     "expr": "otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\", type=\"EXTSHARED\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Write Throughput MBs"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "count(fuse_configuration_policy_system{systemId=~\"[[systemId]]\",} and on (policyId) fuse_configuration_policy_active == 1)",
     "legendFormat": "Configuration Policies"
    },
    {
     "expr": "sum(otcs_system_configurations_count{systemId=~\"[[systemId]]\",})",
     "legendFormat": "System Configurations"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\",} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\",}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",systemId=~\"[[systemId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(count by (envId, alertname, severity) (ALERTS{systemId=~\"[[systemId]]\",alertname=~\"trace_files\",severity=\"warning\"} unless ignoring (severity) ALERTS{systemId=~\"[[systemId]]\",alertname=~\"trace_files\",severity=\"error\"} or ALERTS{systemId=~\"[[systemId]]\",alertname=~\"trace_files\",severity=\"error\"})) * sum(otcs_resource_trace_files_total{systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Logs - Trace Counter Alert"
    },
    {
     "expr": "avg(otcs_db_query_execution_time{componentClass=\"db_performance\",systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Avg. Query Performance"
    },
    {
     "expr": "max(otcs_heartbeat_last_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Last Heart Beat"
    },
    {
     "expr": "max(fuse_maintenance_window_start_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Maintenance Mode"
    },
    {
     "expr": "max(otcs_csidemode_last_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Last CSIDE Mode"
    }
   ]
  },
  {
   "title": "Throughput ENTERPRISEARCHIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "otcs_storage_provider_read_throughput{systemId=~\"[[systemId]]\", type=\"ENTERPRISEARCHIVE\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Read Throughput MBs"
    },
    {
     "expr": "otcs_storage_provider_write_throughput{systemId=~\"[[systemId]]\", type=\"ENTERPRISEARCHIVE\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Write Throughput MBs"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(otcs_resource_memory_total{systemId=~\"[[systemId]]\"})",
     "legendFormat": "RAM Total Memory"
    },
    {
     "expr": "sum(otcs_resource_swap_memory_total{systemId=~\"[[systemId]]\"})",
     "legendFormat": "RAM SWAP Total Memory"
    },
    {
     "expr": "sum(otcs_resource_service_uptime{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Service Uptime"
    },
    {
     "expr": "sum(otcs_resource_system_uptime{systemId=~\"[[systemId]]\"})",
     "legendFormat": "System Uptime"
    }
   ]
  },
  {
   "title": "Configurations Policies Compliance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by (policyId) (fuse_configuration_policy_compliance_failures{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Avg. Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}[5m])) / sum(sum_over_time(fuse_system_active{systemId=~\"[[systemId]]\"}[5m]))) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:perf{systemId=~\"[[systemId]]\",}) or vector(0)",
     "legendFormat": "Performance"
    }
   ]
  }
 ]
}