{
 "title": "System Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_env:perf{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Combined"
    },
    {
     "expr": "avg(system_env:otcs_thread_queue_depth_in:avg_perf{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Queue"
    },
    {
     "expr": "avg(system_env:otcs_thread_execution_time:avg_perf{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Avg, Execution Time"
    },
    {
     "expr": "avg(system_env:otcs_thread_execution_time:le1_perf{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Execution Time <= 1 sec."
    },
    {
     "expr": "avg(system_env:otcs_thread_execution_time:le5_perf{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Execution Time <= 5 sec."
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_env:perf{systemId=~\"[[systemId]]\"}",
     "legendFormat": "Combined Performance"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(otcs_thread_queue_depth_in{systemId=~\"[[systemId]]\"})"
    }
   ]
  },
  {
   "title": "Avg. Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(otcs_thread_execution_time_total[1m]))"
    }
   ]
  },
  {
   "title": "Current Execution Time Counters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"}) or otcs_heartbeat_up{systemId=~\"[[systemId]]\"} * 0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(count(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"} <= 1) or otcs_heartbeat_up{systemId=~\"[[systemId]]\"} * 0)",
     "legendFormat": "<= 1 seg."
    },
    {
     "expr": "sum(count(1 < otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"} <= 5) or otcs_heartbeat_up{systemId=~\"[[systemId]]\"} * 0)",
     "legendFormat": "> 1 seg. and <= 5 seg."
    },
    {
     "expr": "sum(count(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"} > 5) or otcs_heartbeat_up{systemId=~\"[[systemId]]\"} * 0)",
     "legendFormat": "> 5 seg."
    }
   ]
  }
 ]
}