{
 "title": "Systems",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\", systemId=~\"[[systemId]]\"}[5m])) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\", systemId=~\"[[systemId]]\"}[5m])) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Avg. CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\", systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Avg. CPU Usage"
    }
   ]
  },
  {
   "title": "Avg. Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_memory_used{envId=~\"[[envId]]\", systemId=~\"[[systemId]]\"} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Avg. Memory Usage"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(fuse_system_active{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Systems"
    },
    {
     "expr": "count(ALERTS{alertname=\"heartbeat_missing\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(fuse_environment_active{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Environments"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(fuse_environment_total_systems{envId=~\"[[envId]]\"}) - sum(fuse_system_active{envId=~\"[[envId]]\"})",
     "legendFormat": "Deactivated"
    },
    {
     "expr": "sum(max by (systemId) (otcs_heartbeat_up{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"} - otcs_heartbeat_pending_restart{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"})) or vector(0)",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(max by (systemId) (otcs_heartbeat_pending_restart{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"})) or vector(0)",
     "legendFormat": "Pending Restart"
    },
    {
     "expr": "max(otcs_heartbeat_last_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Last Heart Beat"
    }
   ]
  },
  {
   "title": "Systems Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(otcs_resource_service_uptime{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "sum by (systemId) (sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[${__range_s}s])) / sum by (systemId) (sum_over_time(fuse_system_active{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[${__range_s}s]))",
     "legendFormat": "Avg. Availability"
    },
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Performance"
    },
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_used{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId) / sum(otcs_resource_memory_total{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"error\"}) by (systemId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"error\"}) by (systemId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "max(otcs_heartbeat_cside_mode{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "CSIDE Mode"
    },
    {
     "expr": "max(otcs_system_admin_server{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Admin Server"
    },
    {
     "expr": "max(otcs_heartbeat_pending_restart) by (systemId)",
     "legendFormat": "Pending Restart"
    },
    {
     "expr": "sum(fuse_system_active{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(otcs_heartbeat_up) by (systemId)",
     "legendFormat": "Heartbeat"
    },
    {
     "expr": "max by(systemId) (fuse_maintenance_window_start_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Maintenance Mode"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(fuse_environment_total_systems{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Total Systems"
    },
    {
     "expr": "sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[5m])) by (envId) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\"}[5m])) by (envId)",
     "legendFormat": "Avg. Availability"
    },
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Performance"
    },
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Threads Usage"
    },
    {
     "expr": "sum(otcs_thread_queue_depth_in{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Queue Depth"
    },
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_used{envId=~\"[[envId]]\"}) by (envId) / sum(otcs_resource_memory_total{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) by (envId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) by (envId) or  0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "max(fuse_environment_active{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(fuse_maintenance_window_start_time{envId=~\"[[envId]]\", systemId=\"\"}) by (envId)",
     "legendFormat": "Maintenance Mode"
    }
   ]
  }
 ]
}