{
 "title": "Threads",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (severity, alertname) (ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",systemId=~\"[[systemId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max(fuse_environment_active{envId=~\".+\"}) by (envId)"
    }
   ]
  },
  {
   "title": "Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(fuse_system_active{systemId=~\".+\",}) by (systemId)"
    },
    {
     "expr": "sum(otcs_heartbeat_up) by (systemId)",
     "legendFormat": "Heartbeat"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",}[5m])) and on(systemId) max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Avg. Threads Usage"
    },
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",} and on (systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Threads Usage ({{envId}})"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(otcs_thread_execution_time_total{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Avg. Execution Time ({{envId}})"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_queue_avg:avg{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queue Average ({{envId}})"
    },
    {
     "expr": "min(system_env:otcs_thread_queue_min:min{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queue Min ({{envId}})"
    },
    {
     "expr": "max(system_env:otcs_thread_queue_max:max{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queue Max ({{envId}})"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in:sum{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queue Depth In ({{envId}})"
    },
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in_max:sum{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Queue Depth Max ({{envId}})"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\"}[$__range]) and on(systemId) max_over_time(otcs_heartbeat_up{systemId=~\"[[systemId]]\"}[$__range])) by (envId, currentRequest))",
     "legendFormat": "{{currentRequest}} ({{envId}})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(otcs_socket_requests_valid_total{systemId=~\"[[systemId]]\",}[1m]) and otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Total Valid Requests ({{envId}})"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_invalid_total{systemId=~\"[[systemId]]\",}[1m]) and otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Total Invalid Requests ({{envId}})"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_timeout_total{systemId=~\"[[systemId]]\",}[1m]) and otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Total Timeout Requests({{envId}})"
    },
    {
     "expr": "sum(otcs_socket_exceptions_total{systemId=~\"[[systemId]]\",} and otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (envId)",
     "legendFormat": "Total Exceptions ({{envId}})"
    }
   ]
  },
  {
   "title": "Actual Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",})",
     "legendFormat": "Actual Usage"
    }
   ]
  },
  {
   "title": "Average Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(system_env:otcs_thread_busy:ratio{systemId=~\"[[systemId]]\",}[5m]))",
     "legendFormat": "Average Usage"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count((otcs_thread_alive{systemId=~\"[[systemId]]\"}) and on (systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId)",
     "legendFormat": "Total Threads"
    }
   ]
  },
  {
   "title": "Threads List",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(otcs_thread_queue_avg{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Queue Average"
    },
    {
     "expr": "sum(otcs_thread_queue_depth_in{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Queue Depth In"
    },
    {
     "expr": "max(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest)",
     "legendFormat": "Request Execution Time"
    },
    {
     "expr": "max(otcs_thread_request_total{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "otcs_thread_alive{systemId=~\"[[systemId]]\",} * on (systemId, threadIndex) group_right max(max by (systemId, threadIndex, runMaxRequest) (label_join(topk by (systemId, threadIndex) (1, max(max_over_time(otcs_thread_request_execution_time_current{systemId=~\"[[systemId]]\",}[$__range]) and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest)), \"runMaxRequest\", \",\", \"currentRequest\"))) by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Longest Request Execution Time"
    },
    {
     "expr": "max(otcs_thread_exceptions_total{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"}) by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Total Errors"
    },
    {
     "expr": "sum(otcs_thread_busy{systemId=~\"[[systemId]]\",} and on(systemId) otcs_heartbeat_up{systemId=~\"[[systemId]]\"})  by (systemId, threadIndex, currentRequest, runMaxRequest)",
     "legendFormat": "Busy"
    }
   ]
  }
 ]
}