spring:
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml
    contexts: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5499/postgres
    username: postgres
    password: pgfuseadmin2019
    hikari:
      maximum-pool-size: 30
  jpa:
    open-in-view: true
    properties:
      temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.order_by.default_null_ordering: last
      default_schema: public
      hibernate:
        jdbc:
          time_zone: UTC
  task:
    execution:
      pool:
        core-size: 32
        max-size: 32
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      "org.quartz.jobStore.driverDelegateClass": org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  mail:
    # required for MailSenderPropertiesConfiguration to load
    host: ""
    properties:
      "mail.smtp.connectiontimeout": "1000"
      "mail.smtp.timeout": "5000"
      "mail.smtp.starttls.enable": "true"

logging:
  group:
    # when changing log level in administration, these are the loggers that will change
    fuse: "io.vilt.fuse"
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS ZZZ

server:
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      timeout: 600

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, info

prometheus:
  http-client:
    pool:
      max-size: 32
      max-per-route: 32
    request:
      connection-request-timeout: 5s
      connect-timeout: 5s
      read-timeout: 60s
    ssl:
      bundle: ${server.ssl.bundle:${http-client.ssl.bundle:}}
      trust-self-signed: ${http-client.ssl.trust-self-signed:false}

otcs:
  http-client:
    pool:
      max-size: 20
      max-per-route: 20
    request:
      connection-request-timeout: 5s
      connect-timeout: 5s
      read-timeout: 60s
    ssl:
      bundle: ${server.ssl.bundle:${http-client.ssl.bundle:}}
      trust-self-signed: ${http-client.ssl.trust-self-signed:false}

  job-execution:
    timeout: 10m
  service-report:
    multi-environment: false

otac:
  http-client:
    pool:
      max-size: 20
      max-per-route: 20
    request:
      connection-request-timeout: 5s
      connect-timeout: 5s
      read-timeout: 60s
    ssl:
      bundle: ${server.ssl.bundle:${http-client.ssl.bundle:}}
      trust-self-signed: ${http-client.ssl.trust-self-signed:false}

integration-channels:
  http-client:
    pool:
      max-size: 20
      max-per-route: 20
    request:
      connection-request-timeout: 5s
      connect-timeout: 5s
      read-timeout: 60s
    ssl:
      bundle: ${server.ssl.bundle:${http-client.ssl.bundle:}}
      trust-self-signed: ${http-client.ssl.trust-self-signed:false}

grafana:
  dashboard:
    base-uris:
      - classpath:grafana/provisioning/dashboards

metrics:
  skip-history: [ "logcollection", "systemresources", "threadstatus", "dbperformance", "metricsinfo" ]
  retention:
    # 31 days
    period: P31D
    # at 01:00 AM every day
    cron: 0 0 1 * * *
  carry:
    # at 01:15 AM every day
    cron: 0 15 1 * * *
  health-status:
    # in minutes, must be a number
    mail-rate: 1
    service-now-rate: 1
    smax-rate: 1

license:
  otcs-path:
    - file:./license/otcs-key.license
    - classpath:license/otcs-key.license
  otac-path:
    - file:./license/otac-key.license
    - classpath:license/otac-key.license

encryptor:
  password: s3cr3t
  # hex string
  salt: 0c6c0c6c0c6c0c6c0c6c0c6c0c6c0c6c

smax:
  # Name: Display Name
  enums:
    urgency:
      TotalLossOfService: Total Loss of Service
      SevereDisruption: Severe Disruption
      SlightDisruption: Slight Disruption
      NoDisruption: No Disruption
    impact:
      Enterprise: Enterprise
      SiteOrDepartment: Site or Department
      MultipleUsers: Multiple Users
      SingleUsers: Single Users
    completionCode:
      SuccessfulDiagnosis: Diagnosed successfully
      NoFaultFound: No fault found
      NoUserResponse: No user response
      NotReproducible: Not reproducible
      OutofScope: Out of scope
      RequestRejected: Request rejected
      Resolvedbyfix: Resolved successfully
      ResolvedWorkaround: Resolved with workaround
      UnabletoSolve: Unable to solve
      WithdrawnbyUser: Withdrawn by user

service-now:
  roles:
    - admin
    - itil_admin
    - itil

http-client:
  ssl:
    bundle: fuse
