{
 "title": "Environments",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",}) or vector(0)",
     "legendFormat": "Performance"
    }
   ]
  },
  {
   "title": "Avg. Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[5m])) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\"}[5m])) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (severity, alertname) (ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(otcs_socket_requests_valid_total{envId=~\"[[envId]]\",}[1m]))",
     "legendFormat": "Total Valid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_invalid_total{envId=~\"[[envId]]\",}[1m]))",
     "legendFormat": "Total Invalid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_timeout_total{envId=~\"[[envId]]\",}[1m]))",
     "legendFormat": "Total Timeout Requests"
    },
    {
     "expr": "sum(otcs_socket_exceptions_total{envId=~\"[[envId]]\",})",
     "legendFormat": "Total Exceptions"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_queue_avg:avg{envId=~\"[[envId]]\",})",
     "legendFormat": "Queue Average"
    },
    {
     "expr": "min(system_env:otcs_thread_queue_min:min{envId=~\"[[envId]]\",})",
     "legendFormat": "Queue Min"
    },
    {
     "expr": "max(system_env:otcs_thread_queue_max:max{envId=~\"[[envId]]\",})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in:sum{envId=~\"[[envId]]\",})",
     "legendFormat": "Queue Depth In"
    },
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in_max:sum{envId=~\"[[envId]]\",})",
     "legendFormat": "Queue Depth Max"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(otcs_resource_memory_used{envId=~\"[[envId]]\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\",})*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",})",
     "legendFormat": "Threads Usage"
    },
    {
     "expr": "avg(avg_over_time(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",}[5m]))",
     "legendFormat": "Avg. Threads Usage"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current{envId=~\"[[envId]]\"}[$__range])) by (envId, currentRequest))",
     "legendFormat": "{{currentRequest}}"
    }
   ]
  },
  {
   "title": "Environments Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(fuse_environment_total_systems{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Total Systems"
    },
    {
     "expr": "sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[5m])) by (envId) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\"}[5m])) by (envId)",
     "legendFormat": "Avg. Availability"
    },
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Performance"
    },
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Threads Usage"
    },
    {
     "expr": "sum(otcs_thread_queue_depth_in{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Queue Depth"
    },
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_used{envId=~\"[[envId]]\"}) by (envId) / sum(otcs_resource_memory_total{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) by (envId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) by (envId) or  0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (envId)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "max(fuse_environment_active{envId=~\"[[envId]]\"}) by (envId)",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}