{
 "title": "Environment Details",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   {
    "name": "barInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "overviewChartBarInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "systemId",
    "label": "System",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "otcsId",
    "label": "OTCS",
    "query": "select id as __value, name as __text from system where app_type='OTCS'"
   },
   {
    "name": "otacId",
    "label": "OTAC",
    "query": "select id as __value, name as __text from system where app_type='OTAC'"
   },
   { "name": "query0" },
   {
    "name": "barIntervalLarge",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Components",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fuse_configuration_policy_system{envId=~\"[[envId]]\",} and on (policyId) fuse_configuration_policy_active == 1)",
     "legendFormat": "Configuration Policies"
    },
    {
     "expr": "sum(otcs_system_configurations_count{envId=~\"[[envId]]\",})",
     "legendFormat": "System Configurations"
    },
    {
     "expr": "sum(otcs_log_files_counter{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Logs - Counter"
    },
    {
     "expr": "sum(otcs_resource_trace_files_total{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Logs - Trace Counter"
    },
    {
     "expr": "sum(otcs_log_files_total_size{envId=~\"[[envId]]\"})",
     "legendFormat": "Logs - Total Size"
    },
    {
     "expr": "sum(otcs_loaderprocess_count{envId=~\"[[envId]]\",})",
     "legendFormat": "Loaders"
    },
    {
     "expr": "sum(max by (envId) (otcs_agent_count{envId=~\"[[envId]]\",}))",
     "legendFormat": "Agents"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_agents_total_count{envId=~\"[[envId]]\",}))",
     "legendFormat": "Distributed Agents - Agents"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_workers_total_count{envId=~\"[[envId]]\",}))",
     "legendFormat": "Distributed Agents - Workers"
    },
    {
     "expr": "sum(otcs_sov_process_count{envId=~\"[[envId]]\",})",
     "legendFormat": "System Object Volume"
    },
    {
     "expr": "count(otcs_storage_provider_available{envId=~\"[[envId]]\", type=\"RDBMS\"})  by (envId, name, type)",
     "legendFormat": "RDBMS"
    },
    {
     "expr": "count(otcs_storage_provider_available{envId=~\"[[envId]]\", type=\"EXTSHARED\"}) by (envId, name, type)",
     "legendFormat": "EXTSHARED"
    },
    {
     "expr": "count(otcs_storage_provider_available{envId=~\"[[envId]]\", type=\"ENTERPRISEARCHIVE\"}) by (envId, name, type)",
     "legendFormat": "ENTERPRISEARCHIVE"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) \r\nALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "avg by(componentId, type) (otcs_storage_provider_read_throughput{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by(componentId, type) (otcs_storage_provider_write_throughput{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Write Throughput"
    },
    {
     "expr": "avg by(componentId, type) (otcs_storage_provider_disk_space_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Disk Total Space"
    },
    {
     "expr": "avg by(componentId, type) (otcs_storage_provider_disk_space_used{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Disk Used Space"
    },
    {
     "expr": "sum(otcs_resource_memory_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(otcs_resource_swap_memory_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Swap Memory"
    },
    {
     "expr": "sum(otcs_system_logical_processor{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Logical Processor"
    },
    {
     "expr": "sum(otcs_system_physical_processor{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Physical Processor"
    },
    {
     "expr": "count(count by (envId, alertname, severity) (ALERTS{envId=~\"[[envId]]\",alertname=~\"trace_files\",severity=\"warning\"} unless ignoring (severity) ALERTS{envId=~\"[[envId]]\",alertname=~\"trace_files\",severity=\"error\"} or ALERTS{envId=~\"[[envId]]\",alertname=~\"trace_files\",severity=\"error\"})) * sum(otcs_resource_trace_files_total{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Logs - Trace Counter Alert"
    },
    {
     "expr": "avg(otcs_db_query_execution_time{componentClass=\"db_performance\",envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Avg. Query Performance"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otcsId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otcsId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings OTCS"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",systemId=~\"[[otcsId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors OTCS"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings OTAC"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors OTAC"
    },
    {
     "expr": "avg by(componentId, type) (otcs_storage_provider_file_size{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. File Size"
    },
    {
     "expr": "sum(fuse_maintenance_window_start_time{envId=~\"[[envId]]\", systemId=\"\"}) by (envId)",
     "legendFormat": "Maintenance Mode"
    },
    {
     "expr": "max(otcs_heartbeat_last_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Last Heart Beat"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by (severity, alertname, componentId, systemId, envId) (ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) \r\nALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"})",
     "legendFormat": "{{severity}} - {{alertname}}"
    }
   ]
  },
  {
   "title": "Systems Table",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_uptime{envId=~\"[[envId]]\"}) by (systemId)",
     "legendFormat": "Status"
    },
    {
     "expr": "avg by (systemId) (system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",})",
     "legendFormat": "Threads Usage"
    },
    {
     "expr": "avg(otcs_resource_system_cpu_load{envId=~\"[[envId]]\",} ) by (systemId)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_used{envId=~\"[[envId]]\"}) by (systemId) / sum(otcs_resource_memory_total{envId=~\"[[envId]]\"}) by (systemId)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",severity=\"error\"}) by (systemId, envId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (systemId, envId)",
     "legendFormat": "Errors"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"warning\"}  unless ignoring (severity) ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",severity=\"error\"}) by (systemId, envId) or 0 * count(otcs_heartbeat_up{envId=~\"[[envId]]\",}) by (systemId, envId)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "max(otcs_heartbeat_cside_mode{envId=~\"[[envId]]\"}) by (systemId, envId)",
     "legendFormat": "CSIDE Mode"
    },
    {
     "expr": "max(otcs_heartbeat_pending_restart{envId=~\"[[envId]]\",}) by (systemId)",
     "legendFormat": "Pending Restart"
    },
    {
     "expr": "max(fuse_system_active{envId=~\"[[envId]]\"}) by (systemId)",
     "legendFormat": "Active"
    },
    {
     "expr": "avg(otcs_resource_memory_total{envId=~\"[[envId]]\",} ) by (systemId)",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "avg(otcs_resource_swap_memory_total{envId=~\"[[envId]]\",} ) by (systemId)",
     "legendFormat": "Total Swap Memory"
    },
    {
     "expr": "avg(otcs_system_physical_processor{envId=~\"[[envId]]\",} ) by (systemId)",
     "legendFormat": "Total Physical Processor"
    },
    {
     "expr": "avg(otcs_system_logical_processor{envId=~\"[[envId]]\",} ) by (systemId)",
     "legendFormat": "Total Logical Processor"
    },
    {
     "expr": "max by(systemId) (fuse_maintenance_window_start_time{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Maintenance Mode"
    },
    {
     "expr": "sum(otcs_heartbeat_up{envId=~\"[[envId]]\"}) by (systemId)",
     "legendFormat": "Heartbeat"
    }
   ]
  },
  {
   "title": "Components OTAC",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"heartbeat_missing\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\"}) or vector(0)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"warning\"} unless ignoring (severity) \r\nALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",systemId=~\"[[otacId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Overview - Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Overview",
   "type": "barchart",
   "description": "Alerts with performance and availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count by (systemId, alertname, severity) (count_over_time(ALERTS{alertname!~\"__.*\",severity=\"warning\",envId=~\"[[envId]]\", systemId=~\"[[systemId]]\", systemId!~\"\"}[${overviewChartBarInterval}])) OR count by (systemId, alertname, severity) (count_over_time(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",severity=\"warning\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[${overviewChartBarInterval}])))",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(count by (systemId, alertname, severity) (count_over_time(ALERTS{alertname!~\"__.*\",severity=\"error\",envId=~\"[[envId]]\", systemId=~\"[[systemId]]\", systemId!~\"\"}[${overviewChartBarInterval}])) OR count by (systemId, alertname, severity) (count_over_time(ALERTS{alertname!~\"__.*\",severity=\"error\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[${overviewChartBarInterval}])))",
     "legendFormat": "Errors"
    },
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"})*100 or vector(0)",
     "legendFormat": "Performance"
    },
    {
     "expr": "(sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[5m])) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}[5m])))*100 or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(otcs_resource_system_cpu_load{systemId=~\"[[systemId]]\",} and otcs_heartbeat_up{systemId=~\"[[systemId]]\"})*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(otcs_resource_memory_used{systemId=~\"[[systemId]]\"}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(otcs_resource_memory_total{systemId=~\"[[systemId]]\"}) and max(otcs_heartbeat_up{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Components Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"heartbeat_missing\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\"}) or vector(0)",
     "legendFormat": "Offline"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"warning\"} unless ignoring (severity) \r\nALERTS{alertname!~\"__.*\",adminAlert!=\"true\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"^__.*$\",envId=~\"[[envId]]\",systemId=~\"[[systemId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(fuse_maintenance_window_start_time{envId=~\"[[envId]]\", systemId=\"\"}) by (envId)",
     "legendFormat": "Maintenance Mode"
    }
   ]
  },
  { "title": "OTCS - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_env:perf{envId=~\"[[envId]]\",}) or vector(0)",
     "legendFormat": "Performance"
    }
   ]
  },
  {
   "title": "Avg. Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[${__range_s}s])) / sum(sum_over_time(fuse_system_active{envId=~\"[[envId]]\"}[${__range_s}s]))) or vector(0)",
     "legendFormat": "Avg. Availability"
    }
   ]
  },
  {
   "title": "Database Performance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (componentId) (otcs_db_query_execution_time{componentClass=\"db_performance\",envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. {{componentId}}"
    }
   ]
  },
  { "title": "OTCS - Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",}[5m])) and on(envId) max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Threads Usage"
    },
    {
     "expr": "avg(system_env:otcs_thread_busy:ratio{envId=~\"[[envId]]\",}) and on(envId) max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Threads Usage"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(otcs_thread_execution_time_total{envId=~\"[[envId]]\",} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Execution Time"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(otcs_socket_requests_valid_total{envId=~\"[[envId]]\",}[1m])) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Valid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_invalid_total{envId=~\"[[envId]]\",}[1m])) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Invalid Requests"
    },
    {
     "expr": "sum(irate(otcs_socket_requests_timeout_total{envId=~\"[[envId]]\",}[1m])) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Timeout Requests"
    },
    {
     "expr": "sum(otcs_socket_exceptions_total{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Exceptions"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(system_env:otcs_thread_queue_avg:avg{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Queue Average"
    },
    {
     "expr": "min(system_env:otcs_thread_queue_min:min{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Queue Min"
    },
    {
     "expr": "max(system_env:otcs_thread_queue_max:max{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in:sum{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Queue Depth In"
    },
    {
     "expr": "sum(system_env:otcs_thread_queue_depth_in_max:sum{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Queue Depth Max"
    }
   ]
  },
  {
   "title": "Longest Requests",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max(max_over_time(otcs_thread_request_execution_time_current{envId=~\"[[envId]]\"}[$__range]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$__range])) by (envId, currentRequest))",
     "legendFormat": "{{currentRequest}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_env:otcs_thread_busy:ratio:avg_1h{envId=~\"[[envId]]\"} and on(envId) system_env:otcs_heartbeat_up:max_1h{envId=~\".+\"}",
     "legendFormat": "Threads Usage"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max by (envId) (otcs_queuetables_d_tree_notify{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "DTree Notify"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_ll_event_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": " LLEvent Queue"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_notify_events{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Notify Events"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_notify_messages{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Notify Messages"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_provider_retry{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Provider Retry"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_rendition_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Rendition Queue"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_worker_queue{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Worker Queue"
    },
    {
     "expr": "sum(max by (envId) (otcs_queuetables_worker_queue_pending{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}))",
     "legendFormat": "Worker Queue Pending"
    }
   ]
  },
  {
   "title": "Content Status",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (envId, componentName) (topk(5, sum by (envId, componentName) (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type))))) or sort_desc(sum by (envId, componentName) (label_replace(sum  (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type)) - sum (topk(5, sum by (envId, componentName) (max(max_over_time(otcs_content_status_size{envId=~\"[[envId]]\",}[1d])) by (envId, componentName, type)))),\"componentName\",\"Other\",\"componentName\",  \"(.*)\")) > 0)",
     "legendFormat": "{{componentName}}"
    }
   ]
  },
  {
   "title": "Content Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(otcs_content_ingestion{envId=~\"[[envId]]\",}[1d])) or vector(0)",
     "legendFormat": "Total Ingested"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(otcs_users_total_active{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(otcs_workflows_total{envId=~\"[[envId]]\", name=\"activeWorkflows\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) / (sum((max_over_time(otcs_workflows_total{envId=~\"[[envId]]\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) > 0)) or (vector(0))",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(max_over_time(otcs_workflows_total{envId=~\"[[envId]]\", name=\"finishedWorkflows\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) / (sum((max_over_time(otcs_workflows_total{envId=~\"[[envId]]\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) > 0)) or (vector(0))",
     "legendFormat": "Finished"
    },
    {
     "expr": "sum(max_over_time(otcs_workflows_total{envId=~\"[[envId]]\", name=\"archivedWorkflows\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) / (sum((max_over_time(otcs_workflows_total{envId=~\"[[envId]]\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) > 0)) or (vector(0))",
     "legendFormat": "Archived"
    },
    {
     "expr": "sum(max_over_time(otcs_workflows_total{envId=~\"[[envId]]\", name=\"deletedUsersTasks\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) / (sum((max_over_time(otcs_workflows_total{envId=~\"[[envId]]\"}[1d]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[1d])) > 0)) or (vector(0))",
     "legendFormat": "Pending on Deleted Users"
    }
   ]
  },
  {
   "title": "Configurations Policies Compliance",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (policyId) (fuse_configuration_policy_compliance_failures{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Configurations Policies With Systems Compliance",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (policyId, systemId) (fuse_configuration_policy_compliance_failures{systemId=~\"[[systemId]]\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  { "title": "OTCS - Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "System Object Volumes",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"} unless on(envId, componentClass) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\"})) or vector(0) + count(count by (envId) (ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"}\n)) or vector(0)",
     "legendFormat": "Admin Servers Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"} unless on(envId, componentClass) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Admin Servers Active"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"sov_admserv_.*\",envId=~\"[[envId]]\",severity=\"error\"}\r)) or vector(0)",
     "legendFormat": "Admin Servers Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})) or sum(count by (envId) (otcs_sov_processes_status{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Running"
    },
    {
     "expr": "(sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})) or sum(count by (envId) (otcs_sov_processes_status{envId=~\"[[envId]]\"})) or vector(0)) - (sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})) or vector(0))",
     "legendFormat": "Processes Errors"
    },
    {
     "expr": "sum(max by (envId) (otcs_sov_partition_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Partitions Total"
    },
    {
     "expr": "sum( max by (envId) (otcs_sov_partition_count{envId=~\"[[envId]]\"}) and on (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=~\"partition|search_federator\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Partitions Errors"
    },
    {
     "expr": "sum( max by (envId) (otcs_sov_partition_count{envId=~\"[[envId]]\"}) unless on (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=~\"partition|search_federator\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Partitions Active"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_pending{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Pending"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) ((otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}) > 0)) or vector(0)",
     "legendFormat": "iPools Quarantined"
    },
    {
     "expr": "count(count by (envId, alertname, severity) (ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"warning\"} unless ignoring (severity) ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"} or ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"\r})) * sum(count by (envId) ((otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}) > 0)) or vector(0)",
     "legendFormat": "iPools Quarantined Count Alert"
    }
   ]
  },
  {
   "title": "Search Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(otcs_sov_avg_search_time{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Search Time"
    },
    {
     "expr": "max(otcs_sov_total_searches{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Searches"
    }
   ]
  },
  {
   "title": "Ipools",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 36 },
   "targets": [
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_pending{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(max by (id, envId) (max_over_time(otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Quarantined"
    }
   ]
  },
  {
   "title": "Ipools Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_processed{envId=~\"[[envId]]\"})",
     "legendFormat": "Processed"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_pending{envId=~\"[[envId]]\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"})",
     "legendFormat": "Quarantined"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_active{envId=~\"[[envId]]\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Distributed Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(max by (systemId) (otcs_da_agents_total_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Agents Total"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"da_agent_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Agents Errors"
    },
    {
     "expr": "sum(max by (systemId) (otcs_da_workers_total_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Workers Total"
    },
    {
     "expr": "count(count by (envId) (ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname=~\"da_worker_.*\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Workers Errors"
    },
    {
     "expr": "count (count by(envId) (otcs_da_agents_total_count{envId=~\"[[envId]]\"}))",
     "legendFormat": "Environments"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_backlog{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Backlog"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_queued{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Queued"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_processed{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queue Processed"
    }
   ]
  },
  {
   "title": "Distributed Agents Pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 43 },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (envId) (otcs_da_queue_backlog{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Backlog"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_queued{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(max by (envId) (otcs_da_queue_processed{envId=~\"[[envId]]\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Distributed Agents Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 43 },
   "targets": [
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_processed{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_queued{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(max by (envId) (max_over_time(otcs_da_queue_backlog{envId=~\"[[envId]]\"}[$barInterval]) and on(envId) max_over_time(otcs_heartbeat_up{envId=~\"[[envId]]\"}[$barInterval])))",
     "legendFormat": "Backlog"
    }
   ]
  },
  {
   "title": "Agents Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",severity=\"error\",envId=~\"[[envId]]\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",severity=\"warning\",envId=~\"[[envId]]\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Loaded Components Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 50 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_loaderprocess_alive{envId=~\"[[envId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_loaderprocess_alive{envId=~\"[[envId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_loaderprocess_alive{envId=~\"[[envId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Admin Server Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Processes"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_error{envId=~\"[[envId]]\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_safe_mode{envId=~\"[[envId]]\"})",
     "legendFormat": "Safe Mode"
    }
   ]
  },
  {
   "title": "Processes Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_processes_status{envId=~\"[[envId]]\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Partition Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum by (envId, systemId, componentId, componentName, componentClass) (otcs_sov_partition_available{envId=~\"[[envId]]\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum by (envId, systemId, componentId, componentName, componentClass) (otcs_sov_partition_size_content{envId=~\"[[envId]]\"} * 100)",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum by (envId, systemId, componentId, componentName, componentClass) (otcs_sov_partition_size_metadata{envId=~\"[[envId]]\"} * 100)",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "DA Agents Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"da_agent\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_agent_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Worker Agents Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Enabled"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Errors"
    },
    {
     "expr": "count by (envId, systemId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"da_worker\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (envId, systemId, componentId, componentName, componentClass) (otcs_da_worker_status{envId=~\"[[envId]]\"})",
     "legendFormat": "# Warnings"
    }
   ]
  },
  {
   "title": "Agents Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "count by (componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})"
    },
    {
     "expr": "sum by (componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})"
    },
    {
     "expr": "count by (componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})"
    },
    {
     "expr": "count by (componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"agent\",envId=~\"[[envId]]\",severity=\"error\"}) or 0 * count by (componentId, componentName, componentClass) (otcs_agent_activated{envId=~\"[[envId]]\"})"
    }
   ]
  },
  { "title": "OTCS - Storage Providers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Throughput RDBMS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg by (componentId) (otcs_storage_provider_read_throughput{envId=~\"[[envId]]\", type=\"RDBMS\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by (componentId) (otcs_storage_provider_write_throughput{envId=~\"[[envId]]\", type=\"RDBMS\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Write Throughput"
    }
   ]
  },
  {
   "title": "Throughput ENTERPRISEARCHIVE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by (componentId) (otcs_storage_provider_read_throughput{envId=~\"[[envId]]\", type=\"ENTERPRISEARCHIVE\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by (componentId) (otcs_storage_provider_write_throughput{envId=~\"[[envId]]\", type=\"ENTERPRISEARCHIVE\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Write Throughput"
    }
   ]
  },
  {
   "title": "Throughput EXTSHARED",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by (componentId) (otcs_storage_provider_read_throughput{envId=~\"[[envId]]\", type=\"EXTSHARED\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Read Throughput"
    },
    {
     "expr": "avg by (componentId) (otcs_storage_provider_write_throughput{envId=~\"[[envId]]\", type=\"EXTSHARED\"} and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Write Throughput"
    }
   ]
  },
  { "title": "OTAC - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(increase(otac_read_data_volume_total{envId=~\"[[envId]]\"}[$barIntervalLarge]) * 1000000 and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Read Data Volume"
    },
    {
     "expr": "max(increase(otac_write_data_volume_total{envId=~\"[[envId]]\"}[$barIntervalLarge]) * 1000000 and on(envId) otcs_heartbeat_up{envId=~\"[[envId]]\"}) or vector(0)",
     "legendFormat": "Write Data Volume"
    }
   ]
  },
  {
   "title": "Logical Archives Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otac_archive_total_pools{envId=~\"[[envId]]\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Logical Archives",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 74 },
   "targets": [
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_original_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Original Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_original_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Original Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_original\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Original Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_replicated_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Replicated Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_replicated_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Replicated Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_replicated\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Replicated Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_external_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "External Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otac_external_archives_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "External Active"
    },
    {
     "expr": "count(ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"error\"} or ALERTS{alertname=~\"otac_archive_no_pools\",envId=~\"[[envId]]\",componentClass=~\"otac_archive_external\",severity=\"error\"}) or vector(0)",
     "legendFormat": "External Errors"
    }
   ]
  },
  {
   "title": "Document Pipelines Queues Index",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by (systemId, componentId, componentName, componentClass) (otac_dp_queue_idx{envId=~\"[[envId]]\"})",
     "legendFormat": "Index"
    }
   ]
  }
 ]
}