{
 "title": "Fuse / Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "systemId",
    "label": "Systems",
    "query": "select id as __value, name as __text from system"
   },
   {
    "name": "metricType",
    "label": "Metric",
    "query": "select distinct metrics_type  as __text from last_metrics_info"
   },
   { "name": "systemType", "query": "otcs,otac" }
  ]
 },
 "panels": [
  {
   "title": "Fuse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics Database Query Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(http_client_requests_seconds_sum{uri=~\"^/api/v1/query.*\"}[1m]) / irate(http_client_requests_seconds_count{uri=~\"^/api/v1/query.*\"}[1m]))",
     "legendFormat": "Avg. request time"
    },
    {
     "expr": "max(http_client_requests_seconds_max{uri=~\"^/api/v1/query.*\"})",
     "legendFormat": "Max. request time"
    }
   ]
  },
  {
   "title": "Metrics Database Queries Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_client_requests_seconds_count{uri=~\"^/api/v1/query.*\"}[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Metrics Database Query Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(state) (httpcomponents_httpclient_pool_total_connections{httpclient=\"prometheus\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Avg. Grafana Dashboard Queries Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum{uri=\"/api/grafana/dashboard/{id}/queries\",method=\"POST\",status=\"200\"}[1m])) / sum(irate(http_server_requests_seconds_count{uri=~\"/api/grafana/dashboard/{id}/queries\",method=\"POST\",status=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_http_requests_total{handler=~\"^/api/v1/query.*\",code=\"200\"}[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Avg. Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_http_request_duration_seconds_sum{handler=~\"^/api/v1/query.*\"}[1m])) / sum(irate(prometheus_http_requests_total{handler=~\"^/api/v1/query.*\",code=\"200\"}[1m]))",
     "legendFormat": "Avg. Request Time"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metrics Push Elapsed Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (metricsType) (rate(fuse_system_metrics_push_seconds_sum_total{systemId=~\"[[systemId]]\", metricsType=~\"[[metricType]]\", systemType=~\"[[systemType]]\"}[2m]) / rate(fuse_system_metrics_push_seconds_count_total{systemId=~\"[[systemId]]\", metricsType=~\"[[metricType]]\", systemType=~\"[[systemType]]\"}[2m]))",
     "legendFormat": "{{metricsType}}"
    }
   ]
  },
  {
   "title": "Metrics Push Period",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (metricsType) (1 / rate(fuse_system_metrics_push_seconds_count_total{systemId=~\"[[systemId]]\", metricsType=~\"[[metricType]]\", systemType=~\"[[systemType]]\"}[15m]))",
     "legendFormat": "{{metricsType}}"
    }
   ]
  },
  {
   "title": "Metrics Pull Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(http_client_requests_seconds_count{uri=~\".*/api/v2/fuse/metrics/.*\", systemType=~\"[[systemType]]\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{clientName}}{{uri}}"
    }
   ]
  },
  {
   "title": "Metrics Executing Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(componentId, componentName,remoteSystem) (otcs_metrics_info_executing_time{remoteSystem=~\"[[systemId]]\", status=\"executing\", componentName=~\"[[metricType]]\"})",
     "legendFormat": "{{componentId}}"
    }
   ]
  },
  {
   "title": "Metrics Executing Times Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "max by(componentId, componentName,remoteSystem) (otcs_metrics_info_is_slow{remoteSystem=~\"[[systemId]]\", status=\"executing\", componentName=~\"[[metricType]]\"})",
     "legendFormat": "Is Slow"
    },
    {
     "expr": "max by (componentId, componentName,remoteSystem) (otcs_metrics_info_executing_time{remoteSystem=~\"[[systemId]]\", status=\"executing\", componentName=~\"[[metricType]]\"})",
     "legendFormat": "Execution Time"
    }
   ]
  },
  {
   "title": "Slow Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(componentId, componentName,remoteSystem) (otcs_metrics_info_is_slow{remoteSystem=~\"[[systemId]]\", status=\"executing\", componentName=~\"[[metricType]]\"}) > 0",
     "legendFormat": "{{componentId}} "
    }
   ]
  }
 ]
}