{
 "title": "Fuse Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Process Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fuse_health", "legendFormat": "Active" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "used" },
    {
     "expr": "sum(jvm_memory_committed_bytes)",
     "legendFormat": "committed"
    },
    { "expr": "sum(jvm_memory_max_bytes)", "legendFormat": "max" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "System CPU Usage" },
    { "expr": "process_cpu_usage", "legendFormat": "Process CPU Usage" }
   ]
  },
  {
   "title": "Disk Performance",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum (fuse_health_os_disk_total)",
     "legendFormat": "Disk Total"
    },
    { "expr": "sum (fuse_health_os_disk_free)", "legendFormat": "Disk Free" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1-(fuse_health_os_disk_free/fuse_health_os_disk_total))",
     "legendFormat": "Disk Usage"
    }
   ]
  }
 ]
}