{
 "title": "Opentelemetry traces",
 "tags": [
  "opentelemetry",
  "traces",
  "hyperlens",
  "postgres"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Execution Breakdown Overview - Prom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Execution Breakdown Overview - avg",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_sum{type=\"WebServer\"})/\nsum(hyperlens_spans_duration_seconds_count{type=\"WebServer\"})",
     "legendFormat": "WebServers"
    },
    {
     "expr": "sum(hyperlens_spans_duration_seconds_sum{type=\"Thread\"})/\nsum(hyperlens_spans_duration_seconds_count{type=\"Thread\"})",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(hyperlens_spans_duration_seconds_sum{type=\"Connect\"})/\nsum(hyperlens_spans_duration_seconds_count{type=\"Connect\"})",
     "legendFormat": "Connects"
    }
   ]
  },
  {
   "title": "Execution Breakdown Overview - percent",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{type=\"WebServer\"}) / (\n    sum(hyperlens_spans_duration_seconds_count))",
     "legendFormat": "WebSevers"
    },
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{type=\"Thread\"}) / (\n    sum(hyperlens_spans_duration_seconds_count))",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{type=\"Connect\"}) / (\n    sum(hyperlens_spans_duration_seconds_count))",
     "legendFormat": "Connects"
    }
   ]
  },
  { "title": "Most Active Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Most Active Users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Most Active Users - table",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Most Active Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {}
   ]
  },
  { "title": "Top Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Most Executed Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (10, sum by (func) (hyperlens_spans_duration_seconds_count{root=\"true\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Executed Requests - table",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "topk (10, sum by (func) (hyperlens_spans_duration_seconds_count{root=\"true\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Executed Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk (10, sum by (func) (hyperlens_spans_duration_seconds_count{root=\"true\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Longest Execution Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Longest Execution Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Longest Execution Requests - table",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Longest Execution Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {}
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "User Experience Score Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "( sum(rate(hyperlens_spans_duration_seconds_bucket{le=\"1.5\"}[5m])) + sum(rate(hyperlens_spans_duration_seconds_bucket{le=\"3.0\"}[5m])) )/ 2 / sum(rate(hyperlens_spans_duration_seconds_count[5m]))",
     "legendFormat": "__auto",
     "rawSql": "WITH apdex_data AS (\n  SELECT\n    date_trunc('minute', t.startepoch) AS \"time\",\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) <= 0.8) AS excellent_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 0.8 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 1.5) AS good_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 1.5 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 3) AS fair_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 3 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 6) AS poor_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 6) AS unacceptable_count\n  FROM opentelemetry_spans t\n  WHERE t.trace->'instrumentationLibraryInfo'->>'name' = 'Request'-- timestamp BETWEEN 'start_date' AND 'end_date'  -- replace with your actual date range\n  GROUP BY \"time\"\n)\nselect\n  \"time\",\n  (excellent_count + good_count + (0.5 * fair_count)) / (excellent_count + good_count + fair_count + poor_count + unacceptable_count) AS apdex_score\nFROM apdex_data\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "User Experience Score",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 4, "x": 6, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(hyperlens_spans_duration_seconds_bucket{le=\"1.5\"}) + sum(hyperlens_spans_duration_seconds_bucket{le=\"3.0\"}))/2/sum(hyperlens_spans_duration_seconds_count)",
     "legendFormat": "__auto",
     "rawSql": "WITH apdex_data AS (\n  SELECT\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) <= 0.8) AS excellent_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 0.8 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 1.5) AS good_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 1.5 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 3) AS fair_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 3 AND extract(EPOCH FROM t.endepoch - t.startepoch)  <= 6) AS poor_count,\n    COUNT(*) FILTER (WHERE extract(EPOCH FROM t.endepoch - t.startepoch) > 6) AS unacceptable_count\n  FROM opentelemetry_spans t\n  WHERE t.trace->'instrumentationLibraryInfo'->>'name' = 'Request'-- timestamp BETWEEN 'start_date' AND 'end_date'  -- replace with your actual date range\n)\nselect\n  (excellent_count + good_count + (0.5 * (fair_count))) / (excellent_count + good_count + fair_count + poor_count + unacceptable_count) AS apdex_score\nFROM apdex_data"
    }
   ]
  },
  {
   "title": "# of traces in which errors occurred",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{error=\"true\",root=\"true\"})",
     "legendFormat": "__auto",
     "rawSql": "SELECT COUNT(DISTINCT traceId) FROM opentelemetry_spans\nWHERE trace->'status'->>'statusCode'='ERROR'\n"
    }
   ]
  },
  {
   "title": "Total Spans",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{root=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Span Errors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_count{error=\"true\"})",
     "legendFormat": "__auto",
     "rawSql": "SELECT COUNT(spanid) FROM opentelemetry_spans\nWHERE trace->'status'->>'statusCode'='ERROR'\n"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_sum{root=\"true\"})/sum(hyperlens_spans_duration_seconds_count{root=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "excellent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_bucket{le=\"0.8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "good",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_bucket{le=\"1.5\"}) - sum(hyperlens_spans_duration_seconds_bucket{le=\"0.8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fair",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_bucket{le=\"3.0\"}) - sum(hyperlens_spans_duration_seconds_bucket{le=\"1.5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "poor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_bucket{le=\"6.0\"}) - sum(hyperlens_spans_duration_seconds_bucket{le=\"3.0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "unacceptable",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hyperlens_spans_duration_seconds_bucket{le=\"+Inf\"}) - sum(hyperlens_spans_duration_seconds_bucket{le=\"6.0\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}