{
 "title": "System Object Volume Details",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "envId",
    "label": "Environment",
    "query": "select id as __value, name as __text from environment"
   },
   {
    "name": "overviewChartBarInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "barInterval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Processes Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_processes_status{envId=~\"[[envId]]\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Admin Server Systems Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (envId, systemId, componentId, componentName, componentClass) (otcs_system_admin_server{envId=~\"[[envId]]\"}) > 0",
     "legendFormat": "Admin Server"
    },
    {
     "expr": "sum(otcs_heartbeat_up{envId=~\"[[envId]]\"}) by (systemId)",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "Ipools Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_processed{envId=~\"[[envId]]\"})",
     "legendFormat": "Processed"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_pending{envId=~\"[[envId]]\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"})",
     "legendFormat": "Quarantined"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_active{envId=~\"[[envId]]\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Admin Servers Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Admin Servers Active"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Admin Servers Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})) or sum(count by (envId) (otcs_sov_processes_status{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Total"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Processes Running"
    },
    {
     "expr": "sum(count by (envId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Processes Errors"
    },
    {
     "expr": "sum(max by (envId) (otcs_sov_partition_count{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "Partitions Total"
    },
    {
     "expr": "sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=~\"partition|search_federator\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Partitions Errors"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_pending{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Pending"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) ((otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}) > 0)) or vector(0)",
     "legendFormat": "iPools Quarantined"
    },
    {
     "expr": "count(count by (envId, alertname, severity) (ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"warning\"} unless ignoring (severity) ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"} or ALERTS{envId=~\"[[envId]]\",alertname=~\"sov_ipool_quarantined\",severity=\"error\"})) * sum(count by (envId) ((otcs_sov_ipool_quarantined{envId=~\"[[envId]]\"}) > 0)) or vector(0)",
     "legendFormat": "iPools Quarantined Count Alert"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_active{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Active"
    },
    {
     "expr": "sum(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_processed{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Processed"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver|process\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver|process\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver|process\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Admin Servers/Processes Alerts"
    },
    {
     "expr": "count(max by (envId, componentId, componentName, componentClass) (otcs_sov_ipool_active{envId=~\"[[envId]]\"})) or vector(0)",
     "legendFormat": "iPools Total"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",componentClass=~\"ipool|partition\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",componentClass=~\"ipool|partition\",envId=~\"[[envId]]\",severity=\"error\"} or ALERTS{alertname!~\"__.*\",componentClass=~\"ipool|partition\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "IPools/Partitions Alerts"
    },
    {
     "expr": "sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"ipool\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "iPools Errors"
    },
    {
     "expr": "sum(count by (envId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)",
     "legendFormat": "Processes Warnings"
    },
    {
     "expr": "count(ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"__.*\",componentClass=~\"adminserver\",envId=~\"[[envId]]\",severity=\"error\"}) or vector(0)",
     "legendFormat": "Admin Servers Warnings"
    },
    {
     "expr": "(sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"ipool\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0) ) + (sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"partition\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)) +  (sum(count by (envId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0))",
     "legendFormat": "Data Sources Errors"
    },
    {
     "expr": "(sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"ipool\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"ipool\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0) ) + (sum(count by (envId) (ALERTS{alertname!~\"^__.*$\",componentClass=\"partition\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"partition\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0)) +  (sum(count by (envId, componentId, componentName, componentClass) (ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"warning\"} unless ignoring (severity) ALERTS{alertname!~\"^__.*$\",componentClass=\"process\",envId=~\"[[envId]]\",severity=\"error\"})) or vector(0))",
     "legendFormat": "Data Sources Warnings"
    }
   ]
  },
  {
   "title": "Admin Server Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_active{envId=~\"[[envId]]\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_total{envId=~\"[[envId]]\"})",
     "legendFormat": "Processes"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_running{envId=~\"[[envId]]\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_processes_error{envId=~\"[[envId]]\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_admserv_safe_mode{envId=~\"[[envId]]\"})",
     "legendFormat": "Safe Mode"
    }
   ]
  },
  {
   "title": "Partition Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_partition_available{envId=~\"[[envId]]\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_partition_size_content{envId=~\"[[envId]]\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "max by (envId, componentId, componentName, componentClass) (otcs_sov_partition_size_metadata{envId=~\"[[envId]]\"})",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Partitions Total Avg",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by (envId, componentClass) (max by (envId, componentId, componentName, componentClass) (otcs_sov_partition_size_content{envId=~\"[[envId]]\"}))",
     "legendFormat": "Disk"
    },
    {
     "expr": "avg by (envId, componentClass) (max by (envId, componentId, componentName, componentClass) (otcs_sov_partition_size_metadata{envId=~\"[[envId]]\"}))",
     "legendFormat": "Ram"
    }
   ]
  },
  {
   "title": "Search Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(otcs_sov_avg_search_time{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Avg. Search Time"
    },
    {
     "expr": "max(otcs_sov_total_searches{envId=~\"[[envId]]\",}) and max(otcs_heartbeat_up{envId=~\"[[envId]]\"})",
     "legendFormat": "Total Searches"
    }
   ]
  }
 ]
}